variables:
    BACKUP_BUCKET:
        default: null
        description: the name of the bucket in which we should back things up
        overrides: null
        required: true
    BACKUP_BUCKET_REGION:
        default: null
        description: the region where there vpn backups bucket was created
        overrides: null
        required: true
    VPN_KEY_BUCKET:
        default: null
        description: the name of the bucket in which we should retrieve and/or store vpn keys
        overrides: null
        required: true
    VPN_KEY_BUCKET_REGION:
        default: null
        description: the region where there vpn key bucket was created
        overrides: null
        required: true
    DNS_ZONE:
        default: null
        description: the dns entry for the zone (i.e. example.com)
        overrides: null
        required: true
        type: null
    VPN_SSH_KEY_NAME:
        default: null
        description: What key should the vpn instance be launched with?
        overrides: null
        required: true
        type: null
    VPC_NAME:
        default: my-vpc
        description: null
        overrides: null
        required: true
        type: null
    VPC_OCTETS:
        default: 10.0.0.0
        description: null
        overrides: null
        required: true
        type: null
    PRIVATE_ROUTE_NAME:
        required: true
        description: the name to give to the private route
        default: my-private-route
    PRIVATE_SUBNET_NAME:
        default: my-private-subnet
        description: null
        overrides: null
        required: true
        type: null
    PUBLIC_ROUTE_NAME:
        required: true
        description: the name to give to the public route
        default: my-public-route
    PUBLIC_SUBNET_NAME:
        default: my-public-subnet
        description: null
        overrides: null
        required: true
        type: null
    VPN_NAME:
        default: vpn
        description: the name of the vpn server to launch
        overrides: null
        required: true
    VPN_ACCESS_CIDRS:
        default:
            - 0.0.0.0/0
        description: null
        overrides: null
        required: true
        type: array
    VPN_SSH_ACCESS_CIDRS:
        default:
            - 10.0.0.0/8
        description: The cidrs from where you should be able to ssh in
        overrides: null
        required: true
        type: array
    VPN_INSTANCE_TYPE:
        default: t2.micro
        description: null
        overrides: null
        required: true
        type: null
    TIMEZONE:
        default: America/Chicago
        value: America/Chicago
        description: the timezone the servers should come up in
        overrides: null
        required: true
        type: null
    VPN_BACKUP_CRON:
        default: "0 * * * *"
        description: the cron schedule for backups
        overrides: null
        required: true
        type: string
    ENV:
        default: test
        description: null
        overrides: null
        required: true
        type: null
    REGION:
        default: "INSTANCE::region"
        description: the region we are launching in
        overrides: null
        required: true
        type: string
    VPN_DNS_PREFIX:
        default: vpn
        description: "the dns entry to create for the VPN server (<prefix>.<zone>)"
        overrides: null
        required: true
        type: null
    VPN_AMI_ID:
        description: the ami id of the vpn
        switch: "INSTANCE::region"
        cases:
            us-east-1: ami-1ecae776
            us-west-1: ami-d114f295
            us-west-2: ami-e7527ed7
            eu-west-1: ami-a10897d6
            eu-central-1: ami-a8221fb5
            ap-southeast-1: ami-68d8e93a
            ap-northeast-1: ami-cbf90ecb
            ap-southeast-2: ami-fd9cecc7
            sa-east-1: ami-b52890a8
        type: case
    DATADOG_KEY:
        default: null
        value: null
        description: "If you have a datadog key, enter it here and we will install the agent"
        overrides: null
        required: false
